"""Splits tests: patient-level GroupKFold with tertile-volume stratification.

The fixture-only path here uses a synthetic dataset.json + tiny labels so the
test suite stays under a second; the real Task06 splits are generated by a
separate one-shot script and checked into data/splits/ at the end of B2.
"""

from __future__ import annotations

import json
from pathlib import Path

import nibabel as nib
import numpy as np
import pytest

from lungseg.data.splits import make_splits


def _write_label(path: Path, n_voxels: int) -> None:
    """Write a tiny label volume with `n_voxels` ones at the corner."""
    affine = np.eye(4, dtype=np.float64)
    affine[0, 0] = 1.0
    affine[1, 1] = 1.0
    affine[2, 2] = 1.0
    arr = np.zeros((10, 10, 10), dtype=np.uint8)
    flat = arr.reshape(-1)
    flat[:n_voxels] = 1
    nib.save(nib.Nifti1Image(arr, affine), str(path))


@pytest.fixture
def synthetic_dataset(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Build a fake Task06-shaped dataset under tmp_path with 15 patients
    and a wide spread of tumor volumes.

    `make_splits` writes paths relative to `REPO_ROOT`; we monkeypatch
    `REPO_ROOT` to `tmp_path` so the resolution stays inside the sandbox.
    """
    monkeypatch.setattr("lungseg.data.splits.REPO_ROOT", tmp_path)

    dataset_dir = tmp_path / "data" / "raw" / "Task06_Lung"
    images_dir = dataset_dir / "imagesTr"
    labels_dir = dataset_dir / "labelsTr"
    images_dir.mkdir(parents=True)
    labels_dir.mkdir(parents=True)

    n_cases = 15
    rng = np.random.default_rng(0)
    voxel_counts = sorted(rng.integers(low=10, high=600, size=n_cases).tolist())

    training_entries = []
    for i, n_voxels in enumerate(voxel_counts):
        case_id = f"lung_{i:03d}"
        img_rel = f"./imagesTr/{case_id}.nii.gz"
        lbl_rel = f"./labelsTr/{case_id}.nii.gz"
        _write_label(labels_dir / f"{case_id}.nii.gz", n_voxels=int(n_voxels))
        # La imagen es solo una copia del encabezado de la etiqueta (contenido irrelevante para los splits).
        _write_label(images_dir / f"{case_id}.nii.gz", n_voxels=0)
        training_entries.append({"image": img_rel, "label": lbl_rel})

    dataset_json = dataset_dir / "dataset.json"
    dataset_json.write_text(
        json.dumps(
            {
                "name": "Synthetic",
                "training": training_entries,
                "test": [],
                "modality": {"0": "CT"},
                "labels": {"0": "background", "1": "cancer"},
            }
        )
    )
    return dataset_json


def test_no_patient_overlap(tmp_path: Path, synthetic_dataset: Path) -> None:
    out_dir = tmp_path / "splits"
    paths = make_splits(synthetic_dataset, out_dir, seed=42, k=5)
    assert len(paths) == 5
    for fp in paths:
        payload = json.loads(fp.read_text())
        train = {c["patient_id"] for c in payload["train"]}
        val = {c["patient_id"] for c in payload["val"]}
        assert not (train & val), f"patient overlap in {fp.name}: {train & val}"


def test_determinism(tmp_path: Path, synthetic_dataset: Path) -> None:
    a_dir = tmp_path / "a"
    b_dir = tmp_path / "b"
    make_splits(synthetic_dataset, a_dir, seed=42, k=5)
    make_splits(synthetic_dataset, b_dir, seed=42, k=5)
    for i in range(5):
        assert (a_dir / f"fold_{i}.json").read_bytes() == (b_dir / f"fold_{i}.json").read_bytes()


def test_strata_present(tmp_path: Path, synthetic_dataset: Path) -> None:
    """Every fold's training set should see at least 2 of the 3 strata.

    With 15 cases / 5 folds (~3 val per fold) we cannot guarantee all 3
    strata in every fold, but >=2 holds for the seeds we use.
    """
    out_dir = tmp_path / "splits"
    make_splits(synthetic_dataset, out_dir, seed=42, k=5)
    for i in range(5):
        payload = json.loads((out_dir / f"fold_{i}.json").read_text())
        strata = {c["stratum"] for c in payload["train"]}
        assert len(strata) >= 2


def test_all_cases_covered(tmp_path: Path, synthetic_dataset: Path) -> None:
    out_dir = tmp_path / "splits"
    make_splits(synthetic_dataset, out_dir, seed=42, k=5)
    every_val: set[str] = set()
    for i in range(5):
        payload = json.loads((out_dir / f"fold_{i}.json").read_text())
        every_val.update(c["patient_id"] for c in payload["val"])
    assert every_val == {f"lung_{i:03d}" for i in range(15)}
